ALTER TABLE `user`
    ADD COLUMN `subject` VARCHAR(255) NULL DEFAULT NULL AFTER `name`,
    DROP COLUMN `password`;

ALTER TABLE `user`
    ADD UNIQUE INDEX `subject` (`subject`) USING BTREE;

DROP TABLE `token`;
DROP TABLE `SPRING_SESSION_ATTRIBUTES`;
DROP TABLE `SPRING_SESSION`;
