CREATE TABLE IF NOT EXISTS `SPRING_SESSION`
(
    `PRIMARY_ID`            char(36) CHARACTER SET latin2 NOT NULL,
    `SESSION_ID`            char(36) CHARACTER SET latin2 NOT NULL,
    `CREATION_TIME`         bigint(20)                    NOT NULL,
    `LAST_ACCESS_TIME`      bigint(20)                    NOT NULL,
    `MAX_INACTIVE_INTERVAL` int(11)                       NOT NULL,
    `EXPIRY_TIME`           bigint(20)                    NOT NULL,
    `PRINCIPAL_NAME`        varchar(100) DEFAULT NULL,
    PRIMARY KEY (`PRIMARY_ID`),
    UNIQUE KEY `SPRING_SESSION_IX1` (`SESSION_ID`),
    KEY `SPRING_SESSION_IX2` (`EXPIRY_TIME`),
    KEY `SPRING_SESSION_IX3` (`PRINCIPAL_NAME`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS `SPRING_SESSION_ATTRIBUTES`
(
    `SESSION_PRIMARY_ID` char(36) CHARACTER SET latin2     NOT NULL,
    `ATTRIBUTE_NAME`     varchar(200) CHARACTER SET latin2 NOT NULL,
    `ATTRIBUTE_BYTES`    blob                              NOT NULL,
    PRIMARY KEY (`SESSION_PRIMARY_ID`, `ATTRIBUTE_NAME`),
    CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_PRIMARY_ID`) REFERENCES `SPRING_SESSION` (`PRIMARY_ID`) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  ROW_FORMAT = DYNAMIC;